export const DEFAULT_STORIES = [
  {
    "flag_code": "ca",
    "flag_country": "Canada",
    "gender": "male",
    "name": "Simran Vinodkumar Saigal",
    "prev_course": "",
    "prev_college": "",
    "uni": "Thompson Rivers university",
    "course": "Business Administration",
    "destination": "Canada"
  },
  {
    "flag_code": "ca",
    "flag_country": "Canada",
    "gender": "male",
    "name": "Nirav Manoj Arora",
    "prev_course": "",
    "prev_college": "",
    "uni": "University Canada West",
    "course": "Business Administration",
    "destination": "Canada"
  },
  {
    "flag_code": "ca",
    "flag_country": "Canada",
    "gender": "male",
    "name": "Shweta Sunil Nandu",
    "prev_course": "",
    "prev_college": "",
    "uni": "University Canada West",
    "course": "Business Administration",
    "destination": "Canada"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Martin Dsouza",
    "prev_course": "Production Engineering",
    "prev_college": "Fr. Conceicao Rodrigues College of Engineering",
    "uni": "Technische Universität Berlin",
    "course": "Global Production Engineering",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Jash Karanjikar",
    "prev_course": "Chemical Engineering",
    "prev_college": "Thadomal Shahani Engineering College",
    "uni": "Hamburg University of Technology",
    "course": "M.Sc. Environmental Engineering",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "female",
    "name": "Riya Patil",
    "prev_course": "Mechanical Engineering",
    "prev_college": "Vidyavardhini's College Of Engineering & Technology",
    "uni": "Technische Universität Braunschweig",
    "course": "Solar System Physics",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "female",
    "name": "Asmi Save",
    "prev_course": "Microbiology",
    "prev_college": "Thakur Shyamnarayan Degree College",
    "uni": "Universität Leipzig",
    "course": "Biodiversity, Ecology and Evolution",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "female",
    "name": "Avani Chlke",
    "prev_course": "Accounting and Finance",
    "prev_college": "Thakur Shyamnarayan Degree College",
    "uni": "Hochschule Kaiserslautern",
    "course": "MA Financial Services Management",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Jatin Passi",
    "prev_course": "Accounting and Finance",
    "prev_college": "Thakur Shyamnarayan Degree College",
    "uni": "Rhine-Waal University of Applied Sciences",
    "course": "M.Sc. Economics and Finance",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "female",
    "name": "Aashna Naik",
    "prev_course": "Microbiology",
    "prev_college": "Thakur Shyamnarayan Degree College",
    "uni": "RPTU University Kaiserslautern-Landau",
    "course": "MSc Biology with specialization Ecology",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Amod Patil",
    "prev_course": "Automobile Engineering",
    "prev_college": "Pillai College of Engineering",
    "uni": "Coburg University of Applied Sciences",
    "course": "Autonomous Driving",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Jayesh Sharma",
    "prev_course": "Computer Engineering",
    "prev_college": "New Horizon Institute of Technology and Management",
    "uni": "Technische Universität Dresden",
    "course": "Computational Modeling and Simulation",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Shubham Wagh",
    "prev_course": "Mechanical Engineering",
    "prev_college": "Savitribai Phule Pune University",
    "uni": "Technische Hochschule Ingolstadt",
    "course": "Global Foresight and Technology Management",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Abhinit Shetty",
    "prev_course": "EXTC Engineering",
    "prev_college": "Thakur College of Engineering",
    "uni": "Hochschule Bremerhaven",
    "course": "Embedded Systems Design",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Bhavik Singh",
    "prev_course": "EXTC Engineering",
    "prev_college": "Thakur College of Engineering",
    "uni": "Deggendorf Institute of Technology",
    "course": "Electrical Engineering and Information Technology",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Param Agarwal",
    "prev_course": "Mechanical Engineering",
    "prev_college": "Thakur College of Engineering",
    "uni": "Otto von Guericke University Magdeburg",
    "course": "Systems Engineering for Manufacturing",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "female",
    "name": "Abigail Pereira",
    "prev_course": "Information Technology",
    "prev_college": "Sophia College (Autonomous)",
    "uni": "Universität des Saarlandes",
    "course": "MSc Cybersecurity",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "female",
    "name": "Inaaya Khan",
    "prev_course": "Information Technology",
    "prev_college": "Thakur College of Engineering",
    "uni": "Universität des Saarlandes",
    "course": "Computer Science",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Akshat Doshi",
    "prev_course": "Electronics Engineering",
    "prev_college": "Thakur College of Engineering",
    "uni": "Otto von Guericke University Magdeburg",
    "course": "Electrical Engineering and Information Technology",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Maithil Vartak",
    "prev_course": "Mechanical Engineering",
    "prev_college": "Dhole Patil College of Engineering",
    "uni": "University of Siegen",
    "course": "Mechatronics",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "female",
    "name": "Hritvi Chitroda",
    "prev_course": "BA Psychology",
    "prev_college": "Karamveer Bhaurao Patil College",
    "uni": "Universität Leipzig",
    "course": "M.Sc. Sport & Exercise Psychology",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "female",
    "name": "Pauravi Pardeshi",
    "prev_course": "EXTC Engineering",
    "prev_college": "Lokmanya Tilak College of Engineering",
    "uni": "Universität Paderborn",
    "course": "Computer Engineering",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Souma Mondal",
    "prev_course": "EXTC Engineering",
    "prev_college": "Lokmanya Tilak College of Engineering",
    "uni": "Universität Paderborn",
    "course": "Computer Engineering",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Faiz Sayyed",
    "prev_course": "Information Technology",
    "prev_college": "Shree L R Tiwari College of Engineering",
    "uni": "Universität Stuttgart",
    "course": "Computer Science",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Dharmit Vala",
    "prev_course": "Mechanical Engineering",
    "prev_college": "Viva College of Diploma Engineering & Technology",
    "uni": "Otto von Guericke University Magdeburg",
    "course": "Systems Engineering for Manufacturing",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Atharva Paranjape",
    "prev_course": "Computer Engineering",
    "prev_college": "St. Francis Institute of Technology",
    "uni": "Universität Paderborn",
    "course": "Computer Science",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Tejas Dawale",
    "prev_course": "Civil Engineering",
    "prev_college": "Universal College of Engineering",
    "uni": "Magdeburg-Stendal University of Applied Sciences",
    "course": "Water Engineering",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Sonu Bisht",
    "prev_course": "BCom",
    "prev_college": "Thakur College of Science and Commerce",
    "uni": "Berlin School of Business and Innovation",
    "course": "MA in Finance and Investment",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Gagan Pathre",
    "prev_course": "Computer Engineering",
    "prev_college": "Thakur Polytechnic",
    "uni": "Berlin School of Business and Innovation",
    "course": "Computer Science",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Harshal Bankar",
    "prev_course": "Computer Engineering",
    "prev_college": "Thakur Polytechnic",
    "uni": "Berlin School of Business and Innovation",
    "course": "Computer Science",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Atharva Paranjape",
    "prev_course": "Computer Engineering",
    "prev_college": "St. Francis Institute of Technology",
    "uni": "Universität Paderborn",
    "course": "Computer Science",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Tejas Dawale",
    "prev_course": "Civil Engineering",
    "prev_college": "Universal College of Engineering",
    "uni": "Magdeburg-Stendal University of Applied Sciences",
    "course": "Water Engineering",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Sonu Bisht",
    "prev_course": "BCom",
    "prev_college": "Thakur College of Science and Commerce",
    "uni": "Berlin School of Business and Innovation",
    "course": "MA in Finance and Investment",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Gagan Pathre",
    "prev_course": "Computer Engineering",
    "prev_college": "Thakur Polytechnic",
    "uni": "Berlin School of Business and Innovation",
    "course": "Computer Science",
    "destination": "Germany"
  },
  {
    "flag_code": "de",
    "flag_country": "Germany",
    "gender": "male",
    "name": "Harshal Bankar",
    "prev_course": "Computer Engineering",
    "prev_college": "Thakur Polytechnic",
    "uni": "Berlin School of Business and Innovation",
    "course": "Computer Science",
    "destination": "Germany"
  }
] as const;
