import { useState, useRef } from "react";
import { Sparkles, Download, Share2, MessageCircle, GraduationCap, MapPin, Banknote, Loader2, X, CheckCircle2 } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import { generateDreamCard, type DreamCardResult } from "@/lib/dreamcard.functions";

const STUDY_LEVELS = ["Bachelors", "Masters", "MBA", "Diploma", "PhD"];
const COUNTRIES = ["USA", "UK", "Canada", "Australia", "Germany", "Ireland", "New Zealand", "France", "Singapore", "Dubai"];

function Confetti() {
  const pieces = Array.from({ length: 40 }).map((_, i) => ({
    id: i,
    left: `${Math.random() * 100}%`,
    delay: `${Math.random() * 0.6}s`,
    duration: `${1.2 + Math.random() * 1.2}s`,
    color: ["#ff9933", "#138808", "#0a3d91", "#ffffff", "#3B82F6", "#10B981"][i % 6],
    size: 6 + Math.random() * 8,
  }));
  return (
    <div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true">
      {pieces.map((p) => (
        <span
          key={p.id}
          className="absolute top-0 rounded-sm"
          style={{
            left: p.left,
            width: p.size,
            height: p.size * 1.6,
            background: p.color,
            opacity: 0,
            animation: `confetti-fall ${p.duration} ease-out ${p.delay} forwards`,
          }}
        />
      ))}
    </div>
  );
}

export function DreamCard() {
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<DreamCardResult | null>(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const generateFn = useServerFn(generateDreamCard);

  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError("");
    setResult(null);
    setCopied(false);
    const form = e.currentTarget;
    const data = new FormData(form);

    const fullName = String(data.get("full_name") || "").trim();
    const phone = String(data.get("phone") || "").trim();
    const email = String(data.get("email") || "").trim();
    const course = String(data.get("course") || "").trim();
    const country = String(data.get("country") || "").trim();
    const studyLevel = String(data.get("study_level") || "").trim();

    if (!fullName || !course || !country || !studyLevel) {
      setError("Please fill in all required fields.");
      return;
    }
    if (!phone && !email) {
      setError("Please share your phone or email so we can guide you.");
      return;
    }

    let sessionId = "";
    try { sessionId = sessionStorage.getItem("mc_visitor_sid") || ""; } catch { /* ignore */ }

    setBusy(true);
    try {
      const res = await generateFn({ data: { fullName, phone, email, course, country, studyLevel, sessionId } });
      setResult(res);
      form.reset();
      if (typeof window !== "undefined" && typeof (window as any).fbq === "function") {
        (window as any).fbq("track", "Lead");
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong. Try again.");
    } finally {
      setBusy(false);
    }
  };

  const shareText = result
    ? `${result.emoji} ${result.oneLine}\n\nIn 5 years I see myself at ${result.dreamUniversity} studying ${result.dreamCourse} in ${result.dreamCity}, ${result.dreamCountry}.\n\nGenerated by Mission Career — Study Abroad Without the Confusion.\nhttps://missioncareer.net`
    : "";

  const onShare = async () => {
    if (!result) return;
    const url = `https://wa.me/?text=${encodeURIComponent(shareText)}`;
    window.open(url, "_blank", "noopener,noreferrer");
  };

  const onCopy = async () => {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  };

  const onDownload = async () => {
    if (!result || !cardRef.current) return;
    try {
      const { toPng } = await import("html-to-image");
      const dataUrl = await toPng(cardRef.current, { cacheBust: true, pixelRatio: 2 });
      const a = document.createElement("a");
      a.href = dataUrl;
      a.download = "my-dream-card.png";
      a.click();
    } catch {
      onCopy();
    }
  };


  return (
    <section id="dream-card" className="relative overflow-hidden py-16 md:py-24 bg-background">
      <div className="container relative z-10 mx-auto px-4 md:px-8">
        <div className="mx-auto max-w-3xl text-center">
          <span className="inline-flex items-center gap-1.5 rounded-full bg-primary-soft px-4 py-1.5 text-xs md:text-sm font-semibold text-primary mb-3">
            <Sparkles className="h-3.5 w-3.5" /> AI Powered
          </span>
          <h2 className="text-3xl md:text-5xl font-extrabold">
            Where Will <span className="text-gradient">You</span> Be in 5 Years?
          </h2>
          <p className="mt-3 md:mt-4 text-sm md:text-base text-muted-foreground">
            Drop your dream course & country. Our AI will reveal your future university, salary, and life abroad.
          </p>
        </div>

        <div className="mt-10 md:mt-14 mx-auto max-w-xl">
          {!result ? (
            <form onSubmit={onSubmit} className="bg-card rounded-2xl md:rounded-3xl shadow-card p-6 md:p-8 space-y-4">
              <div className="grid sm:grid-cols-2 gap-4">
                <div>
                  <label htmlFor="dream-name" className="block text-sm font-medium mb-1.5">Full Name *</label>
                  <input id="dream-name" name="full_name" required maxLength={120} type="text" placeholder="Your name" className="w-full rounded-xl border border-border bg-secondary px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary" />
                </div>
                <div>
                  <label htmlFor="dream-phone" className="block text-sm font-medium mb-1.5">Phone Number *</label>
                  <input id="dream-phone" name="phone" required maxLength={30} type="tel" placeholder="+91 XXXXX XXXXX" className="w-full rounded-xl border border-border bg-secondary px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary" />
                </div>
              </div>
              <div>
                <label htmlFor="dream-email" className="block text-sm font-medium mb-1.5">Email</label>
                <input id="dream-email" name="email" maxLength={200} type="email" placeholder="your@email.com" className="w-full rounded-xl border border-border bg-secondary px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary" />
              </div>
              <div className="grid sm:grid-cols-2 gap-4">
                <div>
                  <label htmlFor="dream-country" className="block text-sm font-medium mb-1.5">Preferred Country *</label>
                  <select id="dream-country" name="country" required className="w-full rounded-xl border border-border bg-secondary px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary">
                    <option value="">Select Country</option>
                    {COUNTRIES.map((c) => <option key={c}>{c}</option>)}
                  </select>
                </div>
                <div>
                  <label htmlFor="dream-level" className="block text-sm font-medium mb-1.5">Study Level *</label>
                  <select id="dream-level" name="study_level" required className="w-full rounded-xl border border-border bg-secondary px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary">
                    <option value="">Select Level</option>
                    {STUDY_LEVELS.map((l) => <option key={l}>{l}</option>)}
                  </select>
                </div>
              </div>
              <div>
                <label htmlFor="dream-course" className="block text-sm font-medium mb-1.5">Dream Course *</label>
                <input id="dream-course" name="course" required maxLength={120} type="text" placeholder="e.g. Data Science, MBA, Nursing" className="w-full rounded-xl border border-border bg-secondary px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary" />
              </div>
              {error && <p className="text-sm text-destructive">{error}</p>}
              <button disabled={busy} className="w-full inline-flex items-center justify-center gap-2 rounded-full bg-gradient-primary px-6 py-3.5 font-bold text-primary-foreground shadow-soft hover:shadow-glow transition-shadow disabled:opacity-60">
                {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
                {busy ? "Revealing your future…" : "Reveal My Future"}
              </button>
              <p className="text-xs text-muted-foreground text-center">
                We’ll WhatsApp you a free counseling plan based on your dream.
              </p>
            </form>
          ) : (
            <div className="relative">
              <Confetti />
              <div
                ref={cardRef}
                className="relative overflow-hidden rounded-2xl md:rounded-3xl shadow-card p-6 md:p-8 text-white"
                style={{ background: `linear-gradient(135deg, ${result.color} 0%, #1e293b 100%)` }}
              >
                <div className="absolute top-3 right-3">
                  <button onClick={() => setResult(null)} className="rounded-full bg-white/20 p-1.5 hover:bg-white/30 transition">
                    <X className="h-4 w-4" />
                  </button>
                </div>
                <div className="text-center mb-6">
                  <div className="mx-auto h-16 w-16 rounded-full bg-white/20 flex items-center justify-center text-3xl mb-3 animate-bounce">
                    {result.emoji}
                  </div>
                  <h3 className="text-2xl md:text-3xl font-extrabold">{result.oneLine}</h3>
                  <p className="mt-2 text-white/80 text-sm md:text-base">{result.lifestyle}</p>
                </div>

                <div className="grid sm:grid-cols-2 gap-4">
                  <div className="rounded-2xl bg-white/15 backdrop-blur p-4">
                    <div className="flex items-center gap-2 mb-2 text-white/80 text-sm">
                      <GraduationCap className="h-4 w-4" /> University
                    </div>
                    <p className="font-bold text-lg">{result.dreamUniversity}</p>
                    <p className="text-sm text-white/80">{result.dreamCourse}</p>
                  </div>
                  <div className="rounded-2xl bg-white/15 backdrop-blur p-4">
                    <div className="flex items-center gap-2 mb-2 text-white/80 text-sm">
                      <MapPin className="h-4 w-4" /> Location
                    </div>
                    <p className="font-bold text-lg">{result.dreamCity}</p>
                    <p className="text-sm text-white/80">{result.dreamCountry}</p>
                  </div>
                  <div className="rounded-2xl bg-white/15 backdrop-blur p-4 sm:col-span-2">
                    <div className="flex items-center gap-2 mb-2 text-white/80 text-sm">
                      <Banknote className="h-4 w-4" /> Estimated Salary
                    </div>
                    <p className="font-bold text-xl">{result.salaryEstimate}</p>
                    <p className="text-sm text-white/80">Post-graduation average in this field</p>
                  </div>
                </div>

                <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
                  <button onClick={onShare} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-2.5 text-sm font-bold transition hover:scale-105" style={{ color: result.color }}>
                    <MessageCircle className="h-4 w-4" /> Share on WhatsApp
                  </button>
                  <button onClick={onCopy} className="inline-flex items-center gap-2 rounded-full bg-white/20 px-5 py-2.5 text-sm font-bold hover:bg-white/30 transition">
                    {copied ? <CheckCircle2 className="h-4 w-4" /> : <Share2 className="h-4 w-4" />}
                    {copied ? "Copied!" : "Copy Text"}
                  </button>
                  <button onClick={onDownload} className="inline-flex items-center gap-2 rounded-full bg-white/20 px-5 py-2.5 text-sm font-bold hover:bg-white/30 transition">
                    <Download className="h-4 w-4" /> Download
                  </button>
                </div>

                <div className="mt-5 text-center">
                  <a href="https://wa.me/919870003748?text=Hi%20Mission%20Career%2C%20I%20just%20saw%20my%20AI%20dream%20card.%20Guide%20me%20to%20make%20it%20real." target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full border-2 border-white/40 px-6 py-2.5 text-sm font-semibold hover:bg-white/10 transition">
                    <MessageCircle className="h-4 w-4" /> Talk to a counselor on WhatsApp
                  </a>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
