
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS university TEXT,
  ADD COLUMN IF NOT EXISTS course TEXT,
  ADD COLUMN IF NOT EXISTS destination TEXT,
  ADD COLUMN IF NOT EXISTS flag_code TEXT,
  ADD COLUMN IF NOT EXISTS prev_course TEXT,
  ADD COLUMN IF NOT EXISTS prev_college TEXT,
  ADD COLUMN IF NOT EXISTS gender TEXT;
